apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t98u5p0ao-go 
  janus-idp.io/tekton: t98u5p0ao-go
  backstage.io/kubernetes-id: t98u5p0ao-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t98u5p0ao-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  