apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t98u5p0ao-go
  janus-idp.io/tekton: t98u5p0ao-go
  backstage.io/kubernetes-id: t98u5p0ao-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t98u5p0ao-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
